#!/usr/bin/env python3
"""Generate deterministic source metadata for frozen MicroPython modules."""

from __future__ import annotations

import argparse
import subprocess
from pathlib import Path
from typing import Optional

UNKNOWN_VALUE = "unknown"


def _run_git(args: list[str]) -> Optional[str]:
    try:
        result = subprocess.check_output(["git", *args], stderr=subprocess.DEVNULL)
    except (OSError, subprocess.CalledProcessError):
        return None
    return result.decode().strip() or None


def discover_repository() -> str:
    # A clone remote is build-environment metadata, not source identity. Using
    # a canonical upstream URL would also misattribute fork-only commits to the
    # upstream repository, so do not embed a repository URL at all.
    return UNKNOWN_VALUE


def discover_branch() -> str:
    # Branch/tag refs can differ for the same commit (branch checkout, detached
    # HEAD, shallow clone, etc.), so embedding them breaks reproducible builds.
    return UNKNOWN_VALUE


def discover_commit() -> str:
    # Use the full object id. Git's default abbreviated SHA length can vary with
    # the objects present in a clone, so --short is not reproducible.
    commit = _run_git(["rev-parse", "HEAD"])
    if commit:
        return commit
    return UNKNOWN_VALUE


def build_content(repository: str, branch: str, commit: str) -> str:
    return (
        "# This file is auto-generated by tools/embed_git_info.py\n"
        "REPOSITORY = %r\n"
        "BRANCH = %r\n"
        "COMMIT = %r\n" % (repository, branch, commit)
    )


def write_git_info(path: Path) -> None:
    repository = discover_repository()
    branch = discover_branch()
    commit = discover_commit()

    content = build_content(repository, branch, commit)

    path.parent.mkdir(parents=True, exist_ok=True)

    try:
        existing = path.read_text()
    except FileNotFoundError:
        existing = None

    if existing == content:
        return

    path.write_text(content)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "output",
        nargs="?",
        default="src/git_info.py",
        help="path to the generated git_info module",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    write_git_info(Path(args.output))


if __name__ == "__main__":
    main()
